#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

if [ "$START_WITH_DEBUGPY" == "yes" ]; then
    exec python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver_plus 0.0.0.0:8000
else
    exec python manage.py runserver_plus 0.0.0.0:8000
fi
