# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/local/django` directory
    directories:
      - 'compose/local/django/'
      - 'compose/production/django/'
    schedule:
      interval: 'monthly'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    groups:
      docker-python:
        patterns:
          - '*'


  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the listed directories
    directories:
      - 'compose/local/node/'
      - 'compose/production/postgres/'
      - 'compose/production/traefik/'
      - 'compose/production/nginx'
    schedule:
      interval: 'monthly'

  # Enable version updates for Docker Compose files
  - package-ecosystem: 'docker-compose'
    directories:
      - '/'
    schedule:
      interval: 'monthly'

  # Enable version updates for Python/uv
  - package-ecosystem: 'uv'
    # Look for a `pyproject.toml` in the `root` directory
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      python:
        update-types:
          - 'minor'
          - 'patch'
